{% macro get_industry_mappings_2003_onwards() %}
{% set industry_mappings = {
    'bbbb': 'Not applicable - less than 16 years old or NILF who last worked more than 5 years ago or never worked',
    '0170': 'AGR-Crop Production',
    '0180': 'AGR-Animal Production And Aquaculture',
	'0190': 'AGR-Forestry Except Logging',
	'0270': 'AGR-Logging',
	'0280': 'AGR-Fishing, Hunting And Trapping',
	'0290': 'AGR-Support Activities For Agriculture And Forestry',
	'0370': 'EXT-Oil And Gas Extraction',
	'0380': 'EXT-Coal Mining',
	'0390': 'EXT-Metal Ore Mining',
	'0470': 'EXT-Nonmetallic Mineral Mining And Quarrying',
	'0490': 'EXT-Support Activities For Mining',
	'0570': 'UTL-Electric Power Generation, Transmission And Distribution',
	'0580': 'UTL-Natural Gas Distribution',
	'0590': 'UTL-Electric And Gas, And Other Combinations',
	'0670': 'UTL-Water, Steam, Air-Conditioning, And Irrigation Systems',
	'0680': 'UTL-Sewage Treatment Facilities',
	'0690': 'UTL-Not Specified Utilities',
	'0770': 'CON-Construction - The Cleaning Of Buildings And Dwellings Is Incidental During Construction And Immediately After Construction',
	'1070': 'MFG-Animal Food, Grain And Oilseed Milling',
	'1080': 'MFG-Sugar And Confectionery Products',
	'1090': 'MFG-Fruit And Vegetable Preserving And Specialty Food',
	'1170': 'MFG-Dairy Product',
	'1180': 'MFG-Animal Slaughtering And Processing',
	'1190': 'MFG-Retail Bakeries',
	'1270': 'MFG-Bakeries And Tortilla, Except Retail Bakeries',
	'1280': 'MFG-Seafood And Other Miscellaneous Foods, N.E.C.',
	'1290': 'MFG-Not Specified Food Industries',
	'1370': 'MFG-Beverage',
	'1390': 'MFG-Tobacco',
	'1470': 'MFG-Fiber, Yarn, And Thread Mills',
	'1480': 'MFG-Fabric Mills, Except Knitting Mills',
	'1490': 'MFG-Textile And Fabric Finishing And Fabric Coating Mills',
	'1570': 'MFG-Carpet And Rug Mills',
	'1590': 'MFG-Textile Product Mills, Except Carpet And Rug',
	'1670': 'MFG-Knitting Fabric Mills, And Apparel Knitting Mills',
	'1691': 'MFG-Cut And Sew, And Apparel Accessories And Other Apparel',
	'1770': 'MFG-Footwear',
	'1790': 'MFG-Leather And Hide Tanning And Finishing, And Other Leather And Allied Product',
	'1870': 'MFG-Pulp, Paper, And Paperboard Mills',
	'1880': 'MFG-Paperboard Container',
	'1890': 'MFG-Miscellaneous Paper And Pulp Products',
	'1990': 'MFG-Printing And Related Support Activities',
	'2070': 'MFG-Petroleum Refining',
	'2090': 'MFG-Miscellaneous Petroleum And Coal Products',
	'2170': 'MFG-Resin, Synthetic Rubber, And Fibers And Filaments',
	'2180': 'MFG-Agricultural Chemical',
	'2190': 'MFG-Pharmaceutical And Medicine',
	'2270': 'MFG-Paint, Coating, And Adhesive',
	'2280': 'MFG-Soap, Cleaning Compound, And Cosmetics',
	'2290': 'MFG-Industrial And Miscellaneous Chemicals',
	'2370': 'MFG-Plastics Product',
	'2380': 'MFG-Tire',
	'2390': 'MFG-Rubber Products, Except Tires',
	'2470': 'MFG-Pottery, Ceramics, And Plumbing Fixture',
	'2480': 'MFG-Clay Building Material And Refractories',
	'2490': 'MFG-Glass And Glass Product',
	'2570': 'MFG-Cement, Concrete, Lime, And Gypsum Product',
	'2590': 'MFG-Miscellaneous Nonmetallic Mineral Product',
	'2670': 'MFG-Iron And Steel Mills And Steel Product',
	'2680': 'MFG-Aluminum Production And Processing',
	'2690': 'MFG-Nonferrous Metal - Except Aluminum Production And Processing',
	'2770': 'MFG-Foundries',
	'2780': 'MFG-Metal Forgings And Stampings',
	'2790': 'MFG-Cutlery And Hand Tool',
	'2870': 'MFG-Structural Metals, And Boiler, Tank, And Shipping Container',
	'2880': 'MFG-Machine Shops; Turned Product; Screw, Nut, And Bolt',
	'2890': 'MFG-Coating, Engraving, Heat Treating, And Allied Activities',
	'2970': 'MFG-Ordnance',
	'2980': 'MFG-Miscellaneous Fabricated Metal Products',
	'2990': 'MFG-Not Specified Metal Industries',
	'3070': 'MFG-Agricultural Implement',
	'3080': 'MFG-Construction, And Mining And Oil And Gas Field Machinery',
	'3095': 'MFG-Commercial And Service Industry Machinery',
	'3170': 'MFG-Metalworking Machinery',
	'3180': 'MFG-Engine, Turbine, And Power Transmission Equipment',
	'3291': 'MFG-Machinery, N.E.C. Or Not Specified',
	'3365': 'MFG-Computer And Peripheral Equipment',
	'3370': 'MFG-Communications, Audio, And Video Equipment',
	'3380': 'MFG-Navigational, Measuring, Electromedical, And Control Instruments',
	'3390': 'MFG-Electronic Component And Product, N.E.C.',
	'3470': 'MFG-Household Appliance',
	'3490': 'MFG-Electric Lighting And Electrical Equipment, And Other Electrical Component, N.E.C.',
	'3570': 'MFG-Motor Vehicles And Motor Vehicle Equipment',
	'3580': 'MFG-Aircraft And Parts',
	'3590': 'MFG-Aerospace Products And Parts',
	'3670': 'MFG-Railroad Rolling Stock',
	'3680': 'MFG-Ship And Boat Building',
	'3690': 'MFG-Other Transportation Equipment',
	'3770': 'MFG-Sawmills And Wood Preservation',
	'3780': 'MFG-Veneer, Plywood, And Engineered Wood Products',
	'3790': 'MFG-Prefabricated Wood Buildings And Mobile Homes',
	'3875': 'MFG-Miscellaneous Wood Products',
	'3895': 'MFG-Furniture And Related Product',
	'3960': 'MFG-Medical Equipment And Supplies',
	'3970': 'MFG-Sporting And Athletic Goods, And Doll, Toy And Game',
	'3980': 'MFG-Miscellaneous Manufacturing, N.E.C.',
	'3990': 'MFG-Not Specified Manufacturing Industries',
	'4070': 'WHL-Motor Vehicle And Motor Vehicle Parts And Supplies Merchant Wholesalers',
	'4080': 'WHL-Furniture And Home Furnishing Merchant Wholesalers',
	'4090': 'WHL-Lumber And Other Construction Materials Merchant Wholesalers',
	'4170': 'WHL-Professional And Commercial Equipment And Supplies Merchant Wholesalers',
	'4180': 'WHL-Metals And Minerals, Except Petroleum, Merchant Wholesalers',
	'4195': 'WHL-Household Appliances And Electrical And Electronic Goods Merchant Wholesalers',
	'4265': 'WHL-Hardware, And Plumbing And Heating Equipment, And Supplies Merchant Wholesalers',
	'4270': 'WHL-Machinery, Equipment, And Supplies Merchant Wholesalers',
	'4280': 'WHL-Recyclable Material Merchant Wholesalers',
	'4290': 'WHL-Miscellaneous Durable Goods Merchant Wholesalers',
	'4370': 'WHL-Paper And Paper Products Merchant Wholesalers',
	'4380': 'WHL-Drugs, Sundries, And Chemical And Allied Products Merchant Wholesalers',
	'4390': 'WHL-Apparel, Piece Goods, And Notions Merchant Wholesalers',
	'4470': 'WHL-Grocery And Related Product Merchant Wholesalers',
	'4480': 'WHL-Farm Product Raw Material Merchant Wholesalers',
	'4490': 'WHL-Petroleum And Petroleum Products Merchant Wholesalers',
	'4560': 'WHL-Alcoholic Beverages Merchant Wholesalers',
	'4570': 'WHL-Farm Supplies Merchant Wholesalers',
	'4580': 'WHL-Miscellaneous Nondurable Goods Merchant Wholesalers',
	'4585': 'WHL-Wholesale Electronic Markets And Agents And Brokers',
	'4590': 'WHL-Not Specified Wholesale Trade',
	'4670': 'RET-Automobile Dealers',
	'4680': 'RET-Other Motor Vehicle Dealers',
	'4690': 'RET-Automotive Parts, Accessories, And Tire Stores',
	'4770': 'RET-Furniture And Home Furnishings Stores',
	'4780': 'RET-Household Appliance Stores',
	'4795': 'RET-Electronics Stores',
	'4870': 'RET-Building Material And Supplies Dealers',
	'4880': 'RET-Hardware Stores',
	'4890': 'RET-Lawn And Garden Equipment And Supplies Stores',
	'4971': 'RET-Supermarkets and Other Grocery - Except Convenience Stores',
	'4972': 'RET-Convenience Stores',
	'4980': 'RET-Specialty Food Stores',
	'4990': 'RET-Beer, Wine, And Liquor Stores',
	'5070': 'RET-Pharmacies And Drug Stores',
	'5080': 'RET-Health And Personal Care, Except Drug, Stores',
	'5090': 'RET-Gasoline Stations',
	'5170': 'RET-Clothing Stores',
	'5180': 'RET-Shoe Stores',
	'5190': 'RET-Jewelry, Luggage, And Leather Goods Stores',
	'5275': 'RET-Sporting Goods, And Hobby And Toy Stores',
	'5280': 'RET-Sewing, Needlework, And Piece Goods Stores',
	'5295': 'RET-Musical Instrument And Supplies Stores',
	'5370': 'RET-Book Stores And News Dealers',
	'5381': 'RET-Department Stores',
	'5391': 'RET-General Merchandise Stores, Including Warehouse Clubs and Supercenters',
	'5470': 'RET-Florists',
	'5480': 'RET-Office Supplies And Stationery Stores',
	'5490': 'RET-Used Merchandise Stores',
	'5570': 'RET-Gift, Novelty, And Souvenir Shops',
	'5580': 'RET-Miscellaneous Retail Stores',
	'5593': 'RET-Electronic Shopping And Mail-Order Houses',
	'5670': 'RET-Vending Machine Operators',
	'5680': 'RET-Fuel Dealers',
	'5690': 'RET-Other Direct Selling Establishments',
	'5790': 'RET-Not Specified Retail Trade',
	'6070': 'TRN-Air Transportation',
	'6080': 'TRN-Rail Transportation',
	'6090': 'TRN-Water Transportation',
	'6170': 'TRN-Truck Transportation',
	'6180': 'TRN-Bus Service And Urban Transit',
	'6190': 'TRN-Taxi And Limousine Service',
	'6270': 'TRN-Pipeline Transportation',
	'6280': 'TRN-Scenic And Sightseeing Transportation',
	'6290': 'TRN-Services Incidental To Transportation',
	'6370': 'TRN-Postal Service',
	'6380': 'TRN-Couriers And Messengers',
	'6390': 'TRN-Warehousing And Storage',
	'6470': 'INF-Newspaper Publishers',
	'6480': 'INF-Periodical, Book, And Directory Publishers',
	'6490': 'INF-Software Publishers',
	'6570': 'INF-Motion Pictures And Video Industries',
	'6590': 'INF-Sound Recording Industries',
	'6670': 'INF-Broadcasting - Except Internet',
	'6672': 'INF-Internet Publishing And Broadcasting And Web Search Portals',
	'6680': 'INF-Wired Telecommunications Carriers',
	'6690': 'INF-Telecommunications, Except Wired Telecommunications Carriers',
	'6695': 'INF-Data Processing, Hosting, And Related Services',
	'6770': 'INF-Libraries And Archives',
	'6780': 'INF-Other Information Services, Except Libraries And Archives, And Internet Publishing And Broadcasting And Web Search Portals',
	'6870': 'FIN-Banking And Related Activities',
	'6880': 'FIN-Savings Institutions, Including Credit Unions',
	'6890': 'FIN-Nondepository Credit And Related Activities',
	'6970': 'FIN-Securities, Commodities, Funds, Trusts, And Other Financial Investments',
	'6991': 'FIN-Insurance Carriers',
	'6992': 'FIN-Agencies, Brokerages, And Other Insurance Related Activities',
	'7071': 'FIN-Lessors Of Real Estate, And Offices Of Real Estate Agents And Brokers',
	'7072': 'FIN-Real Estate Property Managers, Offices Of Real Estate Appraisers, And Other Activities Related To Real Estate',
	'7080': 'FIN-Automotive Equipment Rental And Leasing',
	'7181': 'FIN-Other Consumer Goods Rental',
	'7190': 'FIN-Commercial, Industrial, And Other Intangible Assets Rental And Leasing',
	'7270': 'PRF-Legal Services',
	'7280': 'PRF-Accounting, Tax Preparation, Bookkeeping, And Payroll Services',
	'7290': 'PRF-Architectural, Engineering, And Related Services',
	'7370': 'PRF-Specialized Design Services',
	'7380': 'PRF-Computer Systems Design And Related Services',
	'7390': 'PRF-Management, Scientific, And Technical Consulting Services',
	'7460': 'PRF-Scientific Research And Development Services',
	'7470': 'PRF-Advertising, Public Relations, And Related Services',
	'7480': 'PRF-Veterinary Services',
	'7490': 'PRF-Other Professional, Scientific, And Technical Services',
	'7570': 'PRF-Management Of Companies And Enterprises',
	'7580': 'PRF-Employment Services',
	'7590': 'PRF-Business Support Services',
	'7670': 'PRF-Travel Arrangements And Reservation Services',
	'7680': 'PRF-Investigation And Security Services',
	'7690': 'PRF-Services To Buildings And Dwellings - Except Cleaning During Construction And Immediately After Construction',
	'7770': 'PRF-Landscaping Services',
	'7780': 'PRF-Other Administrative And Other Support Services',
	'7790': 'PRF-Waste Management And Remediation Services',
	'7860': 'EDU-Elementary And Secondary Schools',
	'7870': 'EDU-Colleges, Universities, And Professional Schools, Including Junior Colleges',
	'7880': 'EDU-Business, Technical, And Trade Schools And Training',
	'7890': 'EDU-Other Schools And Instruction, And Educational Support Services',
	'7970': 'MED-Offices Of Physicians',
	'7980': 'MED-Offices Of Dentists',
	'7990': 'MED-Offices Of Chiropractors',
	'8070': 'MED-Offices Of Optometrists',
	'8080': 'MED-Offices Of Other Health Practitioners',
	'8090': 'MED-Outpatient Care Centers',
	'8170': 'MED-Home Health Care Services',
	'8180': 'MED-Other Health Care Services',
	'8191': 'MED-General Medical And Surgical Hospitals, And Specialty - Except Psychiatric And Substance Abuse Hospitals',
	'8192': 'MED-Psychiatric And Substance Abuse Hospitals',
	'8270': 'MED-Nursing Care Facilities - Skilled Nursing Facilities',
	'8290': 'MED-Residential Care Facilities, Except Skilled Nursing Facilities',
	'8370': 'SCA-Individual And Family Services',
	'8380': 'SCA-Community Food And Housing, And Emergency Services',
	'8390': 'SCA-Vocational Rehabilitation Services',
	'8470': 'SCA-Child Day Care Services',
	'8561': 'ENT-Performing Arts Companies',
	'8562': 'ENT-Spectator Sports',
	'8563': 'ENT-Promoters Of Performing Arts, Sports, And Similar Events, Agents And Managers For Artists, Athletes, Entertainers, And Other Public Figures',
	'8564': 'ENT-Independent Artists, Writers, And Performers',
	'8570': 'ENT-Museums, Art Galleries, Historical Sites, And Similar Institutions',
	'8580': 'ENT-Bowling Centers',
	'8590': 'ENT-Other Amusement, Gambling, And Recreation Industries',
	'8660': 'ENT-Traveler Accommodation',
	'8670': 'ENT-Recreational Vehicle Parks And Camps, And Rooming And Boarding Houses, Dormitories, And Workers Camps',
	'8680': 'ENT-Restaurants And Other Food Services',
	'8690': 'ENT-Drinking Places, Alcoholic Beverages',
	'8770': 'SRV-Automotive Repair And Maintenance',
	'8780': 'SRV-Car Washes',
	'8790': 'SRV-Electronic And Precision Equipment Repair And Maintenance',
	'8870': 'SRV-Commercial And Industrial Machinery And Equipment Repair And Maintenance',
	'8891': 'SRV-Personal And Household Goods Repair And Maintenance',
	'8970': 'SRV-Barber Shops',
	'8980': 'SRV-Beauty Salons',
	'8990': 'SRV-Nail Salons And Other Personal Care Services',
	'9070': 'SRV-Drycleaning And Laundry Services',
	'9080': 'SRV-Funeral Homes, And Cemeteries And Crematories',
	'9090': 'SRV-Other Personal Services',
	'9160': 'SRV-Religious Organizations',
	'9170': 'SRV-Civic, Social, Advocacy Organizations, And Grantmaking And Giving Services',
	'9180': 'SRV-Labor Unions',
	'9190': 'SRV-Business, Professional, Political, And Similar Organizations',
	'9290': 'SRV-Private Households',
	'9370': 'ADM-Executive Offices And Legislative Bodies',
	'9380': 'ADM-Public Finance Activities',
	'9390': 'ADM-Other General Government And Support',
	'9470': 'ADM-Justice, Public Order, And Safety Activities',
	'9480': 'ADM-Administration Of Human Resource Programs',
	'9490': 'ADM-Administration Of Environmental Quality And Housing Programs',
	'9570': 'ADM-Administration Of Economic Programs And Space Research',
	'9590': 'ADM-National Security And International Affairs',
	'9670': 'MIL-U.S. Army',
	'9680': 'MIL-U.S. Air Force',
	'9690': 'MIL-U.S. Navy',
	'9770': 'MIL-U.S. Marines',
	'9780': 'MIL-U.S. Coast Guard',
	'9790': 'MIL-Armed Forces, Branch Not Specified',
	'9870': 'MIL-Military Reserves Or National Guard',
	'9920': 'Unemployed, With No Work Experience In The Last 5 Years Or Earlier Or Never Worked'
} %}
{{ return(industry_mappings) }}
{% endmacro %}